---
# role: ca_trust
# file: molecule/resources/playbooks/converge.yml

- name: "Molecule | converge | ca_trust"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
